version: '3.1'
# Creates a local docker repo
services:
  my-registry:
    image: registry:2.6.1
    volumes:
      - registry:/var/lib/registry
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  registry: