version: '3.1'

services:
  teamcity:
    image: jetbrains/teamcity-server:2017.1.2
    volumes:
      - teamcity-server-datadir:/data/teamcity_server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent:2017.1.2
    environment:
      # uses the name set above. get ip itself
      SERVER_URL: http://teamcity:8111
    # adds the capacity to interact with docker - allows it to run anything it can run in an image
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# available volumes
volumes:
  teamcity-server-datadir:
  teamcity-server-logs: